project_id = "pvllyltruyxahhawxyao"

[functions.mapbox-token]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.robots-txt]
verify_jwt = false

[functions.request-indexing]
verify_jwt = false
